# Generated by Django 3.1.3 on 2021-03-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equiplist',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('controlno', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('model', models.TextField()),
                ('serial', models.TextField()),
                ('maker', models.CharField(max_length=255)),
                ('roomname', models.CharField(max_length=255)),
                ('roomno', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'equiplist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='pmmasterlist',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=255)),
                ('controlno', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
                ('maker', models.CharField(max_length=255)),
                ('roomname', models.CharField(max_length=255)),
                ('roomno', models.CharField(max_length=255)),
                ('revno', models.CharField(default='0', max_length=255)),
                ('date', models.CharField(default='None', max_length=255)),
                ('freq', models.CharField(default='None', max_length=255)),
                ('ra', models.CharField(max_length=255)),
                ('sheetno', models.CharField(default='None', max_length=255)),
                ('amd', models.CharField(default='None', max_length=255)),
                ('itemno', models.CharField(max_length=255)),
                ('item', models.TextField(default='None')),
                ('check', models.TextField(default='None')),
                ('remark', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pmmasterlist',
                'managed': False,
            },
        ),
    ]
