# Generated by Django 3.1.3 on 2021-03-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='controlformlist',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('controlno', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('revno', models.CharField(default='0', max_length=255)),
                ('revdate', models.CharField(default='None', max_length=255)),
                ('pname', models.CharField(default='None', max_length=255)),
                ('pdate', models.CharField(default='Unapproved', max_length=255)),
                ('rname', models.CharField(default='None', max_length=255)),
                ('rdate', models.CharField(default='Unapproved', max_length=255)),
                ('aname', models.CharField(default='None', max_length=255)),
                ('adate', models.CharField(default='Unapproved', max_length=255)),
            ],
            options={
                'db_table': 'equiplist',
                'managed': False,
            },
        ),
    ]
