# Generated by Django 3.1.3 on 2021-03-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_controlformlist'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='controlformlist',
            table='controlformlist',
        ),
    ]
