# Generated by Django 3.1.3 on 2021-03-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_auto_20210309_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='pmmasterlist_temp',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=255)),
                ('controlno', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
                ('maker', models.CharField(max_length=255)),
                ('roomname', models.CharField(max_length=255)),
                ('roomno', models.CharField(max_length=255)),
                ('revno', models.CharField(default='0', max_length=255)),
                ('date', models.CharField(default='None', max_length=255)),
                ('freq', models.CharField(default='None', max_length=255)),
                ('ra', models.CharField(max_length=255)),
                ('sheetno', models.CharField(default='None', max_length=255)),
                ('amd', models.CharField(default='None', max_length=255)),
                ('itemno', models.CharField(max_length=255)),
                ('item', models.TextField(default='None')),
                ('check', models.TextField(default='None')),
                ('startdate', models.CharField(max_length=255)),
                ('change', models.CharField(default='New', max_length=255)),
                ('itemcode', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pmmasterlist_temp',
                'managed': False,
            },
        ),
    ]
