# Generated by Django 3.1.3 on 2021-03-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_pmmasterlist_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='pmsheetdb',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('pmsheetno', models.CharField(max_length=255)),
                ('startdate', models.CharField(max_length=255)),
                ('freq', models.CharField(max_length=255)),
                ('pmsheetno_temp', models.CharField(max_length=255)),
                ('startdate_temp', models.CharField(max_length=255)),
                ('freq_temp', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pmsheetdb',
                'managed': False,
            },
        ),
    ]
