# Generated by Django 3.1.3 on 2021-03-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0006_pm_sch_pm_sch_temp_pmchecksheet_pmchecksheet_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='pm_reference',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('freq_m_y', models.CharField(max_length=255)),
                ('m_y', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pm_reference',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='pm_sch_temp',
        ),
        migrations.DeleteModel(
            name='pmchecksheet_temp',
        ),
    ]
