# Generated by Django 3.1.3 on 2021-04-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0007_auto_20210329_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='pm_manual',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=255)),
                ('controlno', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('partname', models.CharField(max_length=255)),
                ('url', models.TextField(max_length=255)),
                ('maker', models.CharField(max_length=255)),
                ('userid', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pm_manual',
                'managed': False,
            },
        ),
    ]
