# Generated by Django 3.1.3 on 2021-04-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0011_approval_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='approval_information',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('division', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('auth_team', models.CharField(max_length=255)),
                ('auth_name', models.CharField(max_length=255)),
                ('code_no', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'approval_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='spare_in',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('codeno', models.CharField(max_length=255)),
                ('staff', models.CharField(max_length=255)),
                ('qy', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('in_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'spare_in',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='spare_out',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('codeno', models.CharField(max_length=255)),
                ('staff', models.CharField(max_length=255)),
                ('qy', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('controlno', models.CharField(max_length=255)),
                ('out_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'spare_out',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='spare_parts_list',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('codeno', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('partname', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('modelno', models.TextField()),
                ('spec', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('stock', models.CharField(max_length=255)),
                ('staff', models.CharField(max_length=255)),
                ('attach', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'spare_parts_list',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='approval_info',
        ),
    ]
